---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-telegraf

      telegraf_outputs:
        - name: influxdb_v2
          config:
            - urls = ["unix:///var/run/influxdb.sock"]
            - token = "abcd1234"
            - organization = "MyOrg"
            - bucket = "telegraf"

      telegraf_inputs:
        - name: cpu
          config:
            - percpu = false
          tags:
            - tag1 = "foo"
            - tag2 = "bar"
        - name: disk
          config:
            - mount_points = ["/", "/data"]

        - name: cloudwatch
          config:
            - tagexclude = ["region", "instance_id"]
            - region = "us-east-1"
            - access_key = "ACCESS_KEY"
            - secret_key = "SECRET_KEY"
            - period = "5m"
            - delay = "5m"
            - interval = "5m"
            - namespace = "AWS/EC2"
            - metrics:
              config:
                - names = ["CPUCreditBalance"]
                - dimensions:
                  config:
                    - name = "InstanceId"
                    - value = "i-1234"
